name: Upload mandaRa daily page

on:
  schedule:
    - cron: '20 16 * * *'  # 01:20 (JST)

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.1'

    - name: install R packages with renv
      uses: r-lib/actions/setup-renv@v2

    - name: Run R script
      run: Rscript src/page_list.R
      
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data-raw/pages.json
        git commit -m "Update pages.json" -m "Run on $(date +'%Y-%m-%d %H:%M:%S')"
        git push
